GET http://localhost:5000/api/v1/student

###
GET http://localhost:5000/api/v1/student/?order[]=id&order[]=desc
###
POST http://localhost:5000/api/v1/student/
Content-Type: application/json

{
    "name": "Nguyen Van A",
    "sex": "Nam",
    "email": "example531@gmail.com",
    "phone": "123542458",
    "address": "Ha giang"
}

###
PUT http://localhost:5000/api/v1/student/
Content-Type: application/json

{
    "id": 11,
    "sex": "Nu"
}

###
DELETE  http://localhost:5000/api/v1/student/?ids[0]=11&ids[1]=12